#!/bin/bash

#
# Author	Yann Bayle
# E-mail	bayle.yann@live.fr
# License   MIT
# Created	09/09/2016
# Updated	09/09/2016
# Version	1
# Object	Clean all files generated by vqmm
#

cd ./ThibaultLanglois-VQMM/
make clean
cd ..
rm -r ./tmp
